import type { LibraryItem } from "@shared/lib/library";

// 둘러보기 모드용 소재 라이브러리 데모. 브랜드 프로필 '그린루틴 — 비건 스킨케어' 의 어휘·톤·정책(필수문구·금지어·강요성 CTA 금지)에 맞췄어요.
// 이미지는 Gemini 로 생성한 그린루틴 제품 목업(public/demo/library/*.jpg) — 세럼·클렌저·토너·패드·팩·수분크림.
// savedAt 은 호출 시점 기준 상대 시간(분/일 전)으로 계산해 "방금 전" 같은 표시가 자연스럽게 나오게 함.
const DAY = 86400000;
const HOUR = 3600000;

export function getMockLibraryItems(now: number = Date.now()): LibraryItem[] {
  return [
    {
      id: "cre_demo_serum",
      savedAt: now - 2 * HOUR,
      brand: "그린루틴",
      headline: "한 방울로 채우는 식물성 세럼",
      primary:
        "화학 첨가물 없이 식물성 수분 성분만 담은 세럼이에요. 한 방울이면 결이 보송하게 정돈돼요.\n비건 인증·무향·무색소라 민감한 피부에도 순하게 스며들어요.",
      tone: "warm",
      toneLabel: "감성적",
      ctaId: "LEARN_MORE",
      ctaLabel: "자세히 보기",
      goal: "트래픽",
      target: "20–35세 여성 · 민감성 피부",
      gradient: "linear-gradient(135deg, #8bc48b 0%, #cfe7c4 55%, #f3f1e3 100%)",
      image: "/demo/library/serum.jpg",
      tag: "AI 생성",
    },
    {
      id: "cre_demo_cleanser",
      savedAt: now - 1 * DAY,
      brand: "그린루틴",
      headline: "하루의 끝, 순하게 비우는 클렌저",
      primary:
        "식물성 거품이 결을 부드럽게 감싸 담백하게 마무리돼요. 자극적인 향 대신 무향·무색소로요.\n비건 인증을 받아 매일 써도 부담 없는 클렌저예요.",
      tone: "pro",
      toneLabel: "전문적",
      ctaId: "LEARN_MORE",
      ctaLabel: "자세히 보기",
      goal: "인지도",
      target: "25–38세 · 성분 꼼꼼히 보는 사람",
      gradient: "linear-gradient(135deg, #5a8a5a 0%, #9bbf8a 60%, #e8f4e8 100%)",
      image: "/demo/library/cleanser.jpg",
      tag: "AI 생성",
    },
    {
      id: "cre_demo_toner",
      savedAt: now - 2 * DAY,
      brand: "그린루틴",
      headline: "식물성 토너로 시작하는 아침 루틴",
      primary:
        "자극 없이 결을 정돈하는 무향·무색소 토너. 화학 향료 대신 식물성 수분 성분만 담아 담백하게 마무리돼요.\n비건 인증, 까다로운 피부에도 순하게 스며들어요.",
      tone: "warm",
      toneLabel: "감성적",
      ctaId: "LEARN_MORE",
      ctaLabel: "자세히 보기",
      goal: "참여",
      target: "20–34세 · 스킨케어 입문자",
      gradient: "linear-gradient(135deg, #a8d5a8 0%, #d9ecc8 55%, #fbf7ea 100%)",
      image: "/demo/library/toner.jpg",
      tag: "AI 생성",
    },
    {
      id: "cre_demo_pad",
      savedAt: now - 4 * DAY,
      brand: "그린루틴",
      headline: "바쁜 날엔 토너 패드 한 장",
      primary:
        "토너를 덜어 쓸 시간이 없을 때, 패드 한 장이면 결 정돈 끝이에요. 식물성 수분 성분을 그대로 담았어요.\n비건 인증·무향·무색소라 예민한 날에도 편하게 쓰세요.",
      tone: "trendy",
      toneLabel: "트렌디",
      ctaId: "LEARN_MORE",
      ctaLabel: "자세히 보기",
      goal: "참여",
      target: "20–34세 · 인스타그램 자주 사용",
      gradient: "linear-gradient(135deg, #9bc89b 0%, #c4e3b8 55%, #f1efdf 100%)",
      image: "/demo/library/pad.jpg",
      tag: "AI 생성",
    },
    {
      id: "cre_demo_pack",
      savedAt: now - 6 * DAY,
      brand: "그린루틴",
      headline: "환절기 저녁, 순한 시트 팩으로 쉬어가요",
      primary:
        "건조하고 예민해지는 날, 식물성 수분 성분을 담은 시트 팩으로 결을 부드럽게 달래주세요.\n비건 인증·무향·무색소라 컨디션 안 좋은 날에도 부담 없어요.",
      tone: "warm",
      toneLabel: "감성적",
      ctaId: "LEARN_MORE",
      ctaLabel: "자세히 보기",
      goal: "인지도",
      target: "28–40세 · 지속가능 소비 관심",
      gradient: "linear-gradient(135deg, #4a7a4a 0%, #7ba56b 60%, #d8ead0 100%)",
      image: "/demo/library/pack.jpg",
      tag: "AI 생성",
    },
    {
      id: "cre_demo_cream",
      savedAt: now - 9 * DAY,
      brand: "그린루틴",
      headline: "민감한 피부에도 부담 없는 수분 크림",
      primary:
        "식물성 성분만 담아 바르고 나면 촉촉하게 감기는 무향·무색소 수분 크림이에요. 정기 구독으로 끊김 없이 채울 수도 있어요.\n비건 인증, 정가와 배송 조건은 한눈에 확인할 수 있어요.",
      tone: "pro",
      toneLabel: "전문적",
      ctaId: "SIGN_UP",
      ctaLabel: "구독 알아보기",
      goal: "트래픽",
      target: "25–40세 · 재구매 의향 높은 고객",
      gradient: "linear-gradient(135deg, #6ba36b 0%, #a7cf97 60%, #e9f3df 100%)",
      image: "/demo/library/cream.jpg",
      tag: "AI 생성",
    },
    {
      id: "cre_demo_suncream",
      savedAt: now - 11 * DAY,
      brand: "그린루틴",
      headline: "매일 바르는 순한 식물성 자외선 차단",
      primary:
        "백탁 없이 산뜻하게 발리는 비건 선크림이에요. 끈적임 없이 가볍게, 무향·무색소로 자극은 줄였어요.\n비건 인증, 민감한 피부도 부담 없이 데일리로 쓸 수 있어요.",
      tone: "pro",
      toneLabel: "전문적",
      ctaId: "LEARN_MORE",
      ctaLabel: "자세히 보기",
      goal: "트래픽",
      target: "20–38세 · 데일리 자외선 차단 관심",
      gradient: "linear-gradient(135deg, #7ba56b 0%, #b7d6a0 60%, #eef4e2 100%)",
      image: "/demo/library/suncream.png",
      tag: "AI 생성",
    },
    {
      id: "cre_demo_lipbalm",
      savedAt: now - 13 * DAY,
      brand: "그린루틴",
      headline: "건조한 입술에 촉촉 한 겹",
      primary:
        "식물성 보습 성분을 담은 비건 립밤이에요. 무향으로 자극 없이, 하루 종일 촉촉하게 발려요.\n비건 인증·무색소라 입술에도 순하게 감겨요.",
      tone: "trendy",
      toneLabel: "트렌디",
      ctaId: "LEARN_MORE",
      ctaLabel: "자세히 보기",
      goal: "참여",
      target: "20–34세 · 데일리 입술 케어",
      gradient: "linear-gradient(135deg, #9bc89b 0%, #cce6b8 55%, #f3f1e3 100%)",
      image: "/demo/library/lipbalm.png",
      tag: "AI 생성",
    },
  ];
}
