/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/files/{bucket}/{brandProfileId}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["read"];
        put: operations["write"];
        post?: never;
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/sops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["upsert"];
        delete: operations["remove_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/reference-materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["upsert_1"];
        delete: operations["remove_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["upsert_2"];
        delete: operations["remove_3"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post: operations["upsert_3"];
        delete: operations["remove_4"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["status"];
        put?: never;
        post: operations["complete"];
        delete: operations["reset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post: operations["upsert_4"];
        delete: operations["remove_5"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/influencer-campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_5"];
        put?: never;
        post: operations["upsert_5"];
        delete: operations["remove_6"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/creators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_6"];
        put?: never;
        post: operations["upsert_6"];
        delete: operations["remove_7"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/campaign-launches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_7"];
        put?: never;
        post: operations["upsert_7"];
        delete: operations["remove_8"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/brand-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_8"];
        put?: never;
        post: operations["upsert_8"];
        delete: operations["remove_9"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/auto-relaunch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_9"];
        put?: never;
        post: operations["upsert_9"];
        delete: operations["remove_10"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/ig-messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_10"];
        put?: never;
        post: operations["upsert_10"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/cron-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["record"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exchange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/ig-messages/conversation-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["conversationId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/cron-runs/last-success": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lastSuccess"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/meta-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteConnection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ItemRequestSop: {
            item?: components["schemas"]["Sop"];
        };
        Sop: {
            id: string;
            name: string;
            description?: string;
            sections: Record<string, never>;
            createdAt: string;
            updatedAt: string;
        };
        ItemRequestReferenceMaterial: {
            item?: components["schemas"]["ReferenceMaterial"];
        };
        ReferenceMaterial: {
            id: string;
            brandProfileId: string;
            name: string;
            type: string;
            mimeType: string;
            /** Format: int64 */
            sizeBytes: number;
            storageUrl: string;
            /** Format: int64 */
            uploadedAt: number;
        };
        ItemRequestProduct: {
            item?: components["schemas"]["Product"];
        };
        Product: {
            id: string;
            brandProfileId: string;
            name: string;
            description: string;
            imageUrl?: string;
            price?: string;
            targetUrl?: string;
            /** Format: int64 */
            createdAt: number;
        };
        ItemRequestPersona: {
            item?: components["schemas"]["Persona"];
        };
        Persona: {
            id: string;
            brandProfileId: string;
            name: string;
            /** Format: int32 */
            ageMin?: number;
            /** Format: int32 */
            ageMax?: number;
            genders?: number[];
            location?: string[];
            interests?: string[];
            customerDescription?: string;
        };
        ItemRequestLibraryItem: {
            item?: components["schemas"]["LibraryItem"];
        };
        LibraryItem: {
            id: string;
            /** Format: int64 */
            savedAt: number;
            brand: string;
            headline: string;
            primary: string;
            tone: string;
            toneLabel: string;
            ctaId: string;
            ctaLabel: string;
            goal: string;
            target: string;
            gradient: string;
            image?: string;
            tag: string;
        };
        CampaignEntry: {
            creatorId: string;
            /** @enum {string} */
            stage: "candidate" | "proposed" | "negotiating" | "producing" | "published" | "settled";
            outreachDraft?: string;
            contentGuideline?: string;
            contentUrl?: string;
            performance?: components["schemas"]["Performance"];
            paidAt?: string;
            updatedAt: string;
        };
        InfluencerCampaign: {
            id: string;
            name: string;
            goal: string;
            productId?: string;
            /** Format: double */
            budget?: number;
            startDate?: string;
            endDate?: string;
            brandProfileId: string;
            entries: components["schemas"]["CampaignEntry"][];
            createdAt: string;
        };
        ItemRequestInfluencerCampaign: {
            item?: components["schemas"]["InfluencerCampaign"];
        };
        Performance: {
            campaignId: string;
            /** Format: int32 */
            reach?: number;
            /** Format: int32 */
            clicks?: number;
            /** Format: int32 */
            conversions?: number;
            /** Format: double */
            revenue?: number;
            /** Format: double */
            cost?: number;
            recordedAt: string;
        };
        Creator: {
            id: string;
            handle: string;
            /** @enum {string} */
            platform: "instagram" | "youtube" | "tiktok" | "other";
            displayName?: string;
            avatarUrl?: string;
            category: string[];
            /** Format: int32 */
            followerCount?: number;
            note?: string;
            performanceHistory: components["schemas"]["Performance"][];
            createdAt: string;
        };
        ItemRequestCreator: {
            item?: components["schemas"]["Creator"];
        };
        CampaignLaunch: {
            adSetId: string;
            adId?: string;
            adIds?: string[];
            /** Format: double */
            dailyBudget: number;
            startDate: string;
            endDate: string;
            /** @enum {string} */
            status: "ACTIVE" | "PAUSED";
            /** @enum {string} */
            objective?: "OUTCOME_TRAFFIC" | "OUTCOME_AWARENESS" | "OUTCOME_ENGAGEMENT" | "OUTCOME_LEADS" | "OUTCOME_SALES" | "OUTCOME_APP_PROMOTION";
            goalId?: string;
            skipped?: boolean;
            /** @enum {string} */
            abTestAxis?: "headline" | "primary_text" | "image";
            abTestVariantA?: string;
            abTestVariantB?: Record<string, never>;
            campaignId: string;
        };
        ItemRequestCampaignLaunch: {
            item?: components["schemas"]["CampaignLaunch"];
        };
        BrandProfile: {
            id: string;
            name: string;
            isDefault?: boolean;
            brandDescription?: string;
            tone?: string;
            brandVoice?: string;
            customerVoiceSummary?: string;
            imageGuide?: string;
            copyReferences?: components["schemas"]["CopyReference"][];
            proofPoints?: string[];
            /** Format: double */
            marginRate?: number;
            goal?: components["schemas"]["LagTarget"];
            goals?: components["schemas"]["Goal"][];
            policy?: Record<string, never>;
        };
        CopyReference: {
            id: string;
            text: string;
            /** @enum {string} */
            source: "ig" | "manual";
            createdAt: string;
        };
        Goal: {
            id: string;
            name: string;
            lag: components["schemas"]["LagTarget"];
            leads: components["schemas"]["LeadMetric"][];
            /** Format: int32 */
            periodDays?: number;
            createdAt: string;
        };
        ItemRequestBrandProfile: {
            item?: components["schemas"]["BrandProfile"];
        };
        LagTarget: {
            /** @enum {string} */
            metric: "roas" | "contribution" | "cpa";
            /** Format: double */
            target: number;
        };
        LeadMetric: {
            /** @enum {string} */
            kind: "cpc-max" | "ctr-min";
            /** Format: double */
            value: number;
            /** @enum {string} */
            source: "derived" | "custom";
            reason?: string;
        };
        AutoRelaunchState: {
            enabled: boolean;
            /** Format: int32 */
            cycleCount: number;
            parentCampaignId?: string;
            createdAt: string;
            updatedAt: string;
            campaignId: string;
        };
        ItemRequestAutoRelaunchState: {
            item?: components["schemas"]["AutoRelaunchState"];
        };
        BulkRequest: {
            items?: components["schemas"]["IgMessage"][];
        };
        IgMessage: {
            id: string;
            igUserId: string;
            conversationId: string;
            participantId: string;
            participantHandle?: string;
            fromMe: boolean;
            text?: string;
            attachmentUrl?: string;
            createdAt: string;
        };
        CronRun: {
            job?: string;
            ok?: boolean;
            /** Format: int32 */
            scanned?: number;
            /** Format: int32 */
            settled?: number;
            /** Format: int32 */
            advanced?: number;
            errors?: string[];
            started_at?: string;
            finished_at?: string;
            /** Format: int32 */
            error_count?: number;
        };
        RefreshRequest: {
            refreshToken?: string;
        };
        ExchangeResponse: {
            token?: string;
            /** Format: date-time */
            expiresAt?: string;
            refreshToken?: string;
            /** Format: date-time */
            refreshExpiresAt?: string;
        };
        ExchangeRequest: {
            ownerKey?: string;
            email?: string;
            role?: string;
            metaConnection?: components["schemas"]["MetaConnectionPayload"];
        };
        MetaConnectionPayload: {
            accessToken?: string;
            igAccessToken?: string;
            adAccountId?: string;
            adAccountName?: string;
            pageId?: string;
            pageName?: string;
            pixelId?: string;
            pixelName?: string;
            igUserId?: string;
            igUsername?: string;
        };
        ItemsResponseSop: {
            items?: components["schemas"]["Sop"][];
        };
        ItemsResponseReferenceMaterial: {
            items?: components["schemas"]["ReferenceMaterial"][];
        };
        ItemsResponseProduct: {
            items?: components["schemas"]["Product"][];
        };
        ItemsResponsePersona: {
            items?: components["schemas"]["Persona"][];
        };
        ItemsResponseLibraryItem: {
            items?: components["schemas"]["LibraryItem"][];
        };
        ItemsResponseInfluencerCampaign: {
            items?: components["schemas"]["InfluencerCampaign"][];
        };
        ItemsResponseCreator: {
            items?: components["schemas"]["Creator"][];
        };
        ItemsResponseCampaignLaunch: {
            items?: components["schemas"]["CampaignLaunch"][];
        };
        ItemsResponseBrandProfile: {
            items?: components["schemas"]["BrandProfile"][];
        };
        ItemsResponseAutoRelaunchState: {
            items?: components["schemas"]["AutoRelaunchState"][];
        };
        ItemsResponseIgMessage: {
            items?: components["schemas"]["IgMessage"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket: string;
                brandProfileId: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    write: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket: string;
                brandProfileId: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket: string;
                brandProfileId: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemsResponseSop"];
                };
            };
        };
    };
    upsert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemRequestSop"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    remove_1: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    list_1: {
        parameters: {
            query: {
                brandProfileId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemsResponseReferenceMaterial"];
                };
            };
        };
    };
    upsert_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemRequestReferenceMaterial"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    remove_2: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    list_2: {
        parameters: {
            query: {
                brandProfileId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemsResponseProduct"];
                };
            };
        };
    };
    upsert_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemRequestProduct"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    remove_3: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemsResponsePersona"];
                };
            };
        };
    };
    upsert_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemRequestPersona"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    remove_4: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    complete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemsResponseLibraryItem"];
                };
            };
        };
    };
    upsert_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemRequestLibraryItem"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    remove_5: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    list_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemsResponseInfluencerCampaign"];
                };
            };
        };
    };
    upsert_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemRequestInfluencerCampaign"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    remove_6: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    list_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemsResponseCreator"];
                };
            };
        };
    };
    upsert_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemRequestCreator"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    remove_7: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    list_7: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemsResponseCampaignLaunch"];
                };
            };
        };
    };
    upsert_7: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemRequestCampaignLaunch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    remove_8: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    list_8: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemsResponseBrandProfile"];
                };
            };
        };
    };
    upsert_8: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemRequestBrandProfile"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    remove_9: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    list_9: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemsResponseAutoRelaunchState"];
                };
            };
        };
    };
    upsert_9: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemRequestAutoRelaunchState"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    remove_10: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    list_10: {
        parameters: {
            query: {
                igUserId: string;
                conversationId?: string;
            };
            header?: {
                "X-Internal-Secret"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemsResponseIgMessage"];
                };
            };
        };
    };
    upsert_10: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Secret"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    record: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Secret"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CronRun"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Secret"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExchangeResponse"];
                };
            };
        };
    };
    exchange: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Secret"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExchangeResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    conversationId: {
        parameters: {
            query: {
                igUserId: string;
                participantId: string;
            };
            header?: {
                "X-Internal-Secret"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    lastSuccess: {
        parameters: {
            query: {
                job: string;
            };
            header?: {
                "X-Internal-Secret"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CronRun"];
                };
            };
        };
    };
    deleteConnection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
